repos:
  - repo: local
    hooks:
      - id: conda-env-export
        name: Update Conda environment file
        entry: bash -c 'conda env export -n texture_env > environment.yml'
        language: system
        always_run: true
      - id: env-file-add
        name: Add Conda environment file
        entry: git add environment.yml
        language: system
        always_run: true
        