repos:
  - repo: local
    hooks:
      - id: conda-env-export
        name: Update Conda environment file
        entry: bash -c 'conda env export -n texture-env > environment.yml'
        language: system
        always_run: true
      - id: env-file-add
        name: Add Conda environment file
        entry: git add environment.yml
        language: system
        always_run: true
      - id: conda-requirements-export
        name: Update Conda environment file
        entry: bash -c 'conda list --export -n texture-env > requirements.txt'
        language: system
        always_run: true
      - id: requirements-file-add
        name: Add Conda environment file
        entry: git add requirements.txt
        language: system
        always_run: true
